# Default values for auth-backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
env:
ddenv: production

dns: misakey.com

image:
  repository: misakey/api
  tag:
  pullPolicy: IfNotPresent

digests:
  minimal: "0 8 * * *"
  moderate: "0 * * * *"
  frequent: "*/5 * * * *"

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    certmanager.k8s.io/cluster-issuer: letsencrypt

ingressRoute:
  enabled: true
  maxAge: 600
  allowedSubdomains:
    - app
    - auth

resources:
  limits:
   cpu: 400m
   memory: 1024Mi
  requests:
   cpu: 100m
   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

config:
