FROM nginx:alpine

# copy configuration
COPY nginx.conf /etc/nginx/nginx.conf
COPY sites-enabled /etc/nginx/sites-enabled
COPY includes /etc/nginx/includes
COPY certs /etc/certs

# overwrite configuration
COPY dev/includes/* /etc/nginx/includes/

EXPOSE 80
