FROM nginx:alpine

# copy configuration
COPY preprod/nginx.conf /etc/nginx/nginx.conf
COPY sites-enabled /etc/nginx/sites-enabled
COPY includes /etc/nginx/includes
COPY preprod/sites-enabled/* /etc/nginx/sites-enabled/
COPY preprod/includes/* /etc/nginx/includes/

EXPOSE 80
