FROM nginx:alpine

# copy configuration
COPY production/nginx.conf /etc/nginx/nginx.conf
COPY sites-enabled /etc/nginx/sites-enabled
COPY includes /etc/nginx/includes
COPY production/sites-enabled/* /etc/nginx/sites-enabled/
COPY production/includes/* /etc/nginx/includes/

EXPOSE 80
