version: '2.1'

services:
  box_migrate:
    build:
      context: ../../../../
      dockerfile: Dockerfile
    depends_on:
      box_db:
        condition: service_healthy
    environment:
      - DSN_BOX=postgres://misakey:secret@box_db:5432/box-migration-test?sslmode=disable
      - ENV=development
    command: "box-migrate --goose=up"

  box_db:
    image: postgres:11.4
    ports:
      - 127.0.0.1:5502:5432
    environment:
      - POSTGRES_USER=misakey
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=box-migration-test
      - PGPASSWORD=secret # used for healthcheck
    command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: "pg_isready --host=localhost --username=misakey --dbname=box-migration-test"
      interval: 5s
      retries: 10
