// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlboiler

var TableNames = struct {
	Account                       string
	AuthenticationStep            string
	BackupArchive                 string
	CryptoAction                  string
	Identity                      string
	IdentityNotification          string
	IdentityProfileSharingConsent string
	TotpSecret                    string
	UsedCoupon                    string
	WebauthnCredential            string
}{
	Account:                       "account",
	AuthenticationStep:            "authentication_step",
	BackupArchive:                 "backup_archive",
	CryptoAction:                  "crypto_action",
	Identity:                      "identity",
	IdentityNotification:          "identity_notification",
	IdentityProfileSharingConsent: "identity_profile_sharing_consent",
	TotpSecret:                    "totp_secret",
	UsedCoupon:                    "used_coupon",
	WebauthnCredential:            "webauthn_credential",
}
