// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlboiler

var TableNames = struct {
	BoxKeyShare string
	Event       string
}{
	BoxKeyShare: "box_key_share",
	Event:       "event",
}
