// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlboiler

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null"
	"github.com/volatiletech/sqlboiler/boil"
	"github.com/volatiletech/sqlboiler/queries"
	"github.com/volatiletech/sqlboiler/queries/qm"
	"github.com/volatiletech/sqlboiler/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/strmangle"
	"github.com/volatiletech/sqlboiler/types"
)

// AuthenticationStep is an object representing the database table.
type AuthenticationStep struct {
	ID         int        `boil:"id" json:"id" toml:"id" yaml:"id"`
	IdentityID string     `boil:"identity_id" json:"identity_id" toml:"identity_id" yaml:"identity_id"`
	MethodName string     `boil:"method_name" json:"method_name" toml:"method_name" yaml:"method_name"`
	Metadata   types.JSON `boil:"metadata" json:"metadata" toml:"metadata" yaml:"metadata"`
	CreatedAt  time.Time  `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	CompleteAt null.Time  `boil:"complete_at" json:"complete_at,omitempty" toml:"complete_at" yaml:"complete_at,omitempty"`

	R *authenticationStepR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L authenticationStepL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var AuthenticationStepColumns = struct {
	ID         string
	IdentityID string
	MethodName string
	Metadata   string
	CreatedAt  string
	CompleteAt string
}{
	ID:         "id",
	IdentityID: "identity_id",
	MethodName: "method_name",
	Metadata:   "metadata",
	CreatedAt:  "created_at",
	CompleteAt: "complete_at",
}

// Generated where

type whereHelpertypes_JSON struct{ field string }

func (w whereHelpertypes_JSON) EQ(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertypes_JSON) NEQ(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertypes_JSON) LT(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertypes_JSON) LTE(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertypes_JSON) GT(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertypes_JSON) GTE(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

type whereHelpernull_Time struct{ field string }

func (w whereHelpernull_Time) EQ(x null.Time) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Time) NEQ(x null.Time) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Time) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Time) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }
func (w whereHelpernull_Time) LT(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Time) LTE(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Time) GT(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Time) GTE(x null.Time) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var AuthenticationStepWhere = struct {
	ID         whereHelperint
	IdentityID whereHelperstring
	MethodName whereHelperstring
	Metadata   whereHelpertypes_JSON
	CreatedAt  whereHelpertime_Time
	CompleteAt whereHelpernull_Time
}{
	ID:         whereHelperint{field: "\"authentication_step\".\"id\""},
	IdentityID: whereHelperstring{field: "\"authentication_step\".\"identity_id\""},
	MethodName: whereHelperstring{field: "\"authentication_step\".\"method_name\""},
	Metadata:   whereHelpertypes_JSON{field: "\"authentication_step\".\"metadata\""},
	CreatedAt:  whereHelpertime_Time{field: "\"authentication_step\".\"created_at\""},
	CompleteAt: whereHelpernull_Time{field: "\"authentication_step\".\"complete_at\""},
}

// AuthenticationStepRels is where relationship names are stored.
var AuthenticationStepRels = struct {
	Identity string
}{
	Identity: "Identity",
}

// authenticationStepR is where relationships are stored.
type authenticationStepR struct {
	Identity *Identity
}

// NewStruct creates a new relationship struct
func (*authenticationStepR) NewStruct() *authenticationStepR {
	return &authenticationStepR{}
}

// authenticationStepL is where Load methods for each relationship are stored.
type authenticationStepL struct{}

var (
	authenticationStepAllColumns            = []string{"id", "identity_id", "method_name", "metadata", "created_at", "complete_at"}
	authenticationStepColumnsWithoutDefault = []string{"identity_id", "method_name", "metadata", "complete_at"}
	authenticationStepColumnsWithDefault    = []string{"id", "created_at"}
	authenticationStepPrimaryKeyColumns     = []string{"id"}
)

type (
	// AuthenticationStepSlice is an alias for a slice of pointers to AuthenticationStep.
	// This should generally be used opposed to []AuthenticationStep.
	AuthenticationStepSlice []*AuthenticationStep

	authenticationStepQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	authenticationStepType                 = reflect.TypeOf(&AuthenticationStep{})
	authenticationStepMapping              = queries.MakeStructMapping(authenticationStepType)
	authenticationStepPrimaryKeyMapping, _ = queries.BindMapping(authenticationStepType, authenticationStepMapping, authenticationStepPrimaryKeyColumns)
	authenticationStepInsertCacheMut       sync.RWMutex
	authenticationStepInsertCache          = make(map[string]insertCache)
	authenticationStepUpdateCacheMut       sync.RWMutex
	authenticationStepUpdateCache          = make(map[string]updateCache)
	authenticationStepUpsertCacheMut       sync.RWMutex
	authenticationStepUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single authenticationStep record from the query.
func (q authenticationStepQuery) One(ctx context.Context, exec boil.ContextExecutor) (*AuthenticationStep, error) {
	o := &AuthenticationStep{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: failed to execute a one query for authentication_step")
	}

	return o, nil
}

// All returns all AuthenticationStep records from the query.
func (q authenticationStepQuery) All(ctx context.Context, exec boil.ContextExecutor) (AuthenticationStepSlice, error) {
	var o []*AuthenticationStep

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "sqlboiler: failed to assign all query results to AuthenticationStep slice")
	}

	return o, nil
}

// Count returns the count of all AuthenticationStep records in the query.
func (q authenticationStepQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to count authentication_step rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q authenticationStepQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: failed to check if authentication_step exists")
	}

	return count > 0, nil
}

// Identity pointed to by the foreign key.
func (o *AuthenticationStep) Identity(mods ...qm.QueryMod) identityQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.IdentityID),
	}

	queryMods = append(queryMods, mods...)

	query := Identities(queryMods...)
	queries.SetFrom(query.Query, "\"identity\"")

	return query
}

// LoadIdentity allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (authenticationStepL) LoadIdentity(ctx context.Context, e boil.ContextExecutor, singular bool, maybeAuthenticationStep interface{}, mods queries.Applicator) error {
	var slice []*AuthenticationStep
	var object *AuthenticationStep

	if singular {
		object = maybeAuthenticationStep.(*AuthenticationStep)
	} else {
		slice = *maybeAuthenticationStep.(*[]*AuthenticationStep)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &authenticationStepR{}
		}
		args = append(args, object.IdentityID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &authenticationStepR{}
			}

			for _, a := range args {
				if a == obj.IdentityID {
					continue Outer
				}
			}

			args = append(args, obj.IdentityID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(qm.From(`identity`), qm.WhereIn(`identity.id in ?`, args...))
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Identity")
	}

	var resultSlice []*Identity
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Identity")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for identity")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for identity")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Identity = foreign
		if foreign.R == nil {
			foreign.R = &identityR{}
		}
		foreign.R.AuthenticationSteps = append(foreign.R.AuthenticationSteps, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.IdentityID == foreign.ID {
				local.R.Identity = foreign
				if foreign.R == nil {
					foreign.R = &identityR{}
				}
				foreign.R.AuthenticationSteps = append(foreign.R.AuthenticationSteps, local)
				break
			}
		}
	}

	return nil
}

// SetIdentity of the authenticationStep to the related item.
// Sets o.R.Identity to related.
// Adds o to related.R.AuthenticationSteps.
func (o *AuthenticationStep) SetIdentity(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Identity) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"authentication_step\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"identity_id"}),
		strmangle.WhereClause("\"", "\"", 2, authenticationStepPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.IdentityID = related.ID
	if o.R == nil {
		o.R = &authenticationStepR{
			Identity: related,
		}
	} else {
		o.R.Identity = related
	}

	if related.R == nil {
		related.R = &identityR{
			AuthenticationSteps: AuthenticationStepSlice{o},
		}
	} else {
		related.R.AuthenticationSteps = append(related.R.AuthenticationSteps, o)
	}

	return nil
}

// AuthenticationSteps retrieves all the records using an executor.
func AuthenticationSteps(mods ...qm.QueryMod) authenticationStepQuery {
	mods = append(mods, qm.From("\"authentication_step\""))
	return authenticationStepQuery{NewQuery(mods...)}
}

// FindAuthenticationStep retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindAuthenticationStep(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*AuthenticationStep, error) {
	authenticationStepObj := &AuthenticationStep{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"authentication_step\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, authenticationStepObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: unable to select from authentication_step")
	}

	return authenticationStepObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *AuthenticationStep) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("sqlboiler: no authentication_step provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(authenticationStepColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	authenticationStepInsertCacheMut.RLock()
	cache, cached := authenticationStepInsertCache[key]
	authenticationStepInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			authenticationStepAllColumns,
			authenticationStepColumnsWithDefault,
			authenticationStepColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(authenticationStepType, authenticationStepMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(authenticationStepType, authenticationStepMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"authentication_step\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"authentication_step\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to insert into authentication_step")
	}

	if !cached {
		authenticationStepInsertCacheMut.Lock()
		authenticationStepInsertCache[key] = cache
		authenticationStepInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the AuthenticationStep.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *AuthenticationStep) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	authenticationStepUpdateCacheMut.RLock()
	cache, cached := authenticationStepUpdateCache[key]
	authenticationStepUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			authenticationStepAllColumns,
			authenticationStepPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("sqlboiler: unable to update authentication_step, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"authentication_step\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, authenticationStepPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(authenticationStepType, authenticationStepMapping, append(wl, authenticationStepPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update authentication_step row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by update for authentication_step")
	}

	if !cached {
		authenticationStepUpdateCacheMut.Lock()
		authenticationStepUpdateCache[key] = cache
		authenticationStepUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q authenticationStepQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update all for authentication_step")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to retrieve rows affected for authentication_step")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o AuthenticationStepSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("sqlboiler: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), authenticationStepPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"authentication_step\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, authenticationStepPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update all in authenticationStep slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to retrieve rows affected all in update all authenticationStep")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *AuthenticationStep) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("sqlboiler: no authentication_step provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(authenticationStepColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	authenticationStepUpsertCacheMut.RLock()
	cache, cached := authenticationStepUpsertCache[key]
	authenticationStepUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			authenticationStepAllColumns,
			authenticationStepColumnsWithDefault,
			authenticationStepColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			authenticationStepAllColumns,
			authenticationStepPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("sqlboiler: unable to upsert authentication_step, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(authenticationStepPrimaryKeyColumns))
			copy(conflict, authenticationStepPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"authentication_step\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(authenticationStepType, authenticationStepMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(authenticationStepType, authenticationStepMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to upsert authentication_step")
	}

	if !cached {
		authenticationStepUpsertCacheMut.Lock()
		authenticationStepUpsertCache[key] = cache
		authenticationStepUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single AuthenticationStep record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *AuthenticationStep) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("sqlboiler: no AuthenticationStep provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), authenticationStepPrimaryKeyMapping)
	sql := "DELETE FROM \"authentication_step\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete from authentication_step")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by delete for authentication_step")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q authenticationStepQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("sqlboiler: no authenticationStepQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete all from authentication_step")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by deleteall for authentication_step")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o AuthenticationStepSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), authenticationStepPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"authentication_step\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, authenticationStepPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete all from authenticationStep slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by deleteall for authentication_step")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *AuthenticationStep) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindAuthenticationStep(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *AuthenticationStepSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := AuthenticationStepSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), authenticationStepPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"authentication_step\".* FROM \"authentication_step\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, authenticationStepPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to reload all in AuthenticationStepSlice")
	}

	*o = slice

	return nil
}

// AuthenticationStepExists checks if the AuthenticationStep row exists.
func AuthenticationStepExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"authentication_step\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: unable to check if authentication_step exists")
	}

	return exists, nil
}
