// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlboiler

var TableNames = struct {
	Account            string
	AuthenticationStep string
	Identifier         string
	Identity           string
}{
	Account:            "account",
	AuthenticationStep: "authentication_step",
	Identifier:         "identifier",
	Identity:           "identity",
}
