// Code generated by SQLBoiler 4.2.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package sqlboiler

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// StorageQuotum is an object representing the database table.
type StorageQuotum struct {
	ID         string    `boil:"id" json:"id" toml:"id" yaml:"id"`
	IdentityID string    `boil:"identity_id" json:"identity_id" toml:"identity_id" yaml:"identity_id"`
	Value      int64     `boil:"value" json:"value" toml:"value" yaml:"value"`
	Origin     string    `boil:"origin" json:"origin" toml:"origin" yaml:"origin"`
	CreatedAt  time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *storageQuotumR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L storageQuotumL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var StorageQuotumColumns = struct {
	ID         string
	IdentityID string
	Value      string
	Origin     string
	CreatedAt  string
}{
	ID:         "id",
	IdentityID: "identity_id",
	Value:      "value",
	Origin:     "origin",
	CreatedAt:  "created_at",
}

// Generated where

var StorageQuotumWhere = struct {
	ID         whereHelperstring
	IdentityID whereHelperstring
	Value      whereHelperint64
	Origin     whereHelperstring
	CreatedAt  whereHelpertime_Time
}{
	ID:         whereHelperstring{field: "\"storage_quotum\".\"id\""},
	IdentityID: whereHelperstring{field: "\"storage_quotum\".\"identity_id\""},
	Value:      whereHelperint64{field: "\"storage_quotum\".\"value\""},
	Origin:     whereHelperstring{field: "\"storage_quotum\".\"origin\""},
	CreatedAt:  whereHelpertime_Time{field: "\"storage_quotum\".\"created_at\""},
}

// StorageQuotumRels is where relationship names are stored.
var StorageQuotumRels = struct {
}{}

// storageQuotumR is where relationships are stored.
type storageQuotumR struct {
}

// NewStruct creates a new relationship struct
func (*storageQuotumR) NewStruct() *storageQuotumR {
	return &storageQuotumR{}
}

// storageQuotumL is where Load methods for each relationship are stored.
type storageQuotumL struct{}

var (
	storageQuotumAllColumns            = []string{"id", "identity_id", "value", "origin", "created_at"}
	storageQuotumColumnsWithoutDefault = []string{"id", "identity_id", "value", "origin"}
	storageQuotumColumnsWithDefault    = []string{"created_at"}
	storageQuotumPrimaryKeyColumns     = []string{"id"}
)

type (
	// StorageQuotumSlice is an alias for a slice of pointers to StorageQuotum.
	// This should generally be used opposed to []StorageQuotum.
	StorageQuotumSlice []*StorageQuotum

	storageQuotumQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	storageQuotumType                 = reflect.TypeOf(&StorageQuotum{})
	storageQuotumMapping              = queries.MakeStructMapping(storageQuotumType)
	storageQuotumPrimaryKeyMapping, _ = queries.BindMapping(storageQuotumType, storageQuotumMapping, storageQuotumPrimaryKeyColumns)
	storageQuotumInsertCacheMut       sync.RWMutex
	storageQuotumInsertCache          = make(map[string]insertCache)
	storageQuotumUpdateCacheMut       sync.RWMutex
	storageQuotumUpdateCache          = make(map[string]updateCache)
	storageQuotumUpsertCacheMut       sync.RWMutex
	storageQuotumUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single storageQuotum record from the query.
func (q storageQuotumQuery) One(ctx context.Context, exec boil.ContextExecutor) (*StorageQuotum, error) {
	o := &StorageQuotum{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: failed to execute a one query for storage_quotum")
	}

	return o, nil
}

// All returns all StorageQuotum records from the query.
func (q storageQuotumQuery) All(ctx context.Context, exec boil.ContextExecutor) (StorageQuotumSlice, error) {
	var o []*StorageQuotum

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "sqlboiler: failed to assign all query results to StorageQuotum slice")
	}

	return o, nil
}

// Count returns the count of all StorageQuotum records in the query.
func (q storageQuotumQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to count storage_quotum rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q storageQuotumQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: failed to check if storage_quotum exists")
	}

	return count > 0, nil
}

// StorageQuota retrieves all the records using an executor.
func StorageQuota(mods ...qm.QueryMod) storageQuotumQuery {
	mods = append(mods, qm.From("\"storage_quotum\""))
	return storageQuotumQuery{NewQuery(mods...)}
}

// FindStorageQuotum retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindStorageQuotum(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*StorageQuotum, error) {
	storageQuotumObj := &StorageQuotum{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"storage_quotum\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, storageQuotumObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "sqlboiler: unable to select from storage_quotum")
	}

	return storageQuotumObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *StorageQuotum) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("sqlboiler: no storage_quotum provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(storageQuotumColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	storageQuotumInsertCacheMut.RLock()
	cache, cached := storageQuotumInsertCache[key]
	storageQuotumInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			storageQuotumAllColumns,
			storageQuotumColumnsWithDefault,
			storageQuotumColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(storageQuotumType, storageQuotumMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(storageQuotumType, storageQuotumMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"storage_quotum\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"storage_quotum\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to insert into storage_quotum")
	}

	if !cached {
		storageQuotumInsertCacheMut.Lock()
		storageQuotumInsertCache[key] = cache
		storageQuotumInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the StorageQuotum.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *StorageQuotum) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	storageQuotumUpdateCacheMut.RLock()
	cache, cached := storageQuotumUpdateCache[key]
	storageQuotumUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			storageQuotumAllColumns,
			storageQuotumPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("sqlboiler: unable to update storage_quotum, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"storage_quotum\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, storageQuotumPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(storageQuotumType, storageQuotumMapping, append(wl, storageQuotumPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update storage_quotum row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by update for storage_quotum")
	}

	if !cached {
		storageQuotumUpdateCacheMut.Lock()
		storageQuotumUpdateCache[key] = cache
		storageQuotumUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q storageQuotumQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update all for storage_quotum")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to retrieve rows affected for storage_quotum")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o StorageQuotumSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("sqlboiler: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), storageQuotumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"storage_quotum\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, storageQuotumPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to update all in storageQuotum slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to retrieve rows affected all in update all storageQuotum")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *StorageQuotum) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("sqlboiler: no storage_quotum provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(storageQuotumColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	storageQuotumUpsertCacheMut.RLock()
	cache, cached := storageQuotumUpsertCache[key]
	storageQuotumUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			storageQuotumAllColumns,
			storageQuotumColumnsWithDefault,
			storageQuotumColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			storageQuotumAllColumns,
			storageQuotumPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("sqlboiler: unable to upsert storage_quotum, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(storageQuotumPrimaryKeyColumns))
			copy(conflict, storageQuotumPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"storage_quotum\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(storageQuotumType, storageQuotumMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(storageQuotumType, storageQuotumMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to upsert storage_quotum")
	}

	if !cached {
		storageQuotumUpsertCacheMut.Lock()
		storageQuotumUpsertCache[key] = cache
		storageQuotumUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single StorageQuotum record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *StorageQuotum) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("sqlboiler: no StorageQuotum provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), storageQuotumPrimaryKeyMapping)
	sql := "DELETE FROM \"storage_quotum\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete from storage_quotum")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by delete for storage_quotum")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q storageQuotumQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("sqlboiler: no storageQuotumQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete all from storage_quotum")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by deleteall for storage_quotum")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o StorageQuotumSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), storageQuotumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"storage_quotum\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, storageQuotumPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: unable to delete all from storageQuotum slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "sqlboiler: failed to get rows affected by deleteall for storage_quotum")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *StorageQuotum) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindStorageQuotum(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *StorageQuotumSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := StorageQuotumSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), storageQuotumPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"storage_quotum\".* FROM \"storage_quotum\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, storageQuotumPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "sqlboiler: unable to reload all in StorageQuotumSlice")
	}

	*o = slice

	return nil
}

// StorageQuotumExists checks if the StorageQuotum row exists.
func StorageQuotumExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"storage_quotum\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "sqlboiler: unable to check if storage_quotum exists")
	}

	return exists, nil
}
